#ifndef MESSAGE_QUEUE_CONFIG_H
#define MESSAGE_QUEUE_CONFIG_H

#include "sdkconfig.h"

/* Message Queue component enable/disable switch */
#define MESSAGE_QUEUE_ENABLE CONFIG_MESSAGE_QUEUE_ENABLE

#if (MESSAGE_QUEUE_ENABLE == 1)

#define MESSAGE_QUEUE_MAX_PENDING CONFIG_MESSAGE_QUEUE_MAX_PENDING
#define MESSAGE_QUEUE_MAX_RETRIES CONFIG_MESSAGE_QUEUE_MAX_RETRIES

#endif /* MESSAGE_QUEUE_ENABLE */

#endif /* MESSAGE_QUEUE_CONFIG_H */