#ifndef AUDIO_STORAGE_CONFIG_H
#define AUDIO_STORAGE_CONFIG_H

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Enable/disable audio storage module */
#ifdef CONFIG_PROJECT_ENABLE_AUDIO_STORAGE
#define AUDIO_STORAGE_ENABLE CONFIG_PROJECT_ENABLE_AUDIO_STORAGE
#else
#define AUDIO_STORAGE_ENABLE 1
#endif

#if (AUDIO_STORAGE_ENABLE == 1)

#ifdef CONFIG_PROJECT_AUDIO_STORAGE_BASE_PATH
#define AUDIO_STORAGE_BASE_PATH CONFIG_PROJECT_AUDIO_STORAGE_BASE_PATH
#else
#define AUDIO_STORAGE_BASE_PATH "/audio"
#endif

#ifdef CONFIG_PROJECT_AUDIO_STORAGE_PARTITION_LABEL
#define AUDIO_STORAGE_PARTITION_LABEL CONFIG_PROJECT_AUDIO_STORAGE_PARTITION_LABEL
#else
#define AUDIO_STORAGE_PARTITION_LABEL "audio_storage"
#endif

#ifdef CONFIG_PROJECT_AUDIO_STORAGE_FORMAT_IF_MOUNT_FAILED
#define AUDIO_STORAGE_FORMAT_IF_MOUNT_FAILED CONFIG_PROJECT_AUDIO_STORAGE_FORMAT_IF_MOUNT_FAILED
#else
#define AUDIO_STORAGE_FORMAT_IF_MOUNT_FAILED false
#endif

#endif /* AUDIO_STORAGE_ENABLE */

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_STORAGE_CONFIG_H */
