#ifndef LCD_CONFIG_H
#define LCD_CONFIG_H

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"
#include "sdkconfig.h"

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef CONFIG_PROJECT_LCD_DRIVER_ENABLE
#define RADAR_ENABLE_LCD_DISPLAY 1
#else
#define RADAR_ENABLE_LCD_DISPLAY 0
#endif

#if (RADAR_ENABLE_LCD_DISPLAY == 1)

#if (CONFIG_PROJECT_LCD_SPI_HOST == 1)
#define LCD_SPI_HOST SPI2_HOST
#elif (CONFIG_PROJECT_LCD_SPI_HOST == 2)
#define LCD_SPI_HOST SPI3_HOST
#else
#define LCD_SPI_HOST SPI2_HOST
#endif

#define LCD_SPI_CLOCK_SPEED_HZ (CONFIG_PROJECT_LCD_SPI_CLOCK_SPEED * 1000000)
#define LCD_SPI_MOSI_GPIO CONFIG_PROJECT_LCD_SPI_MOSI_GPIO
#define LCD_SPI_SCLK_GPIO CONFIG_PROJECT_LCD_SPI_SCLK_GPIO
#define LCD_SPI_CS_GPIO CONFIG_PROJECT_LCD_SPI_CS_GPIO
#define LCD_SPI_DC_GPIO CONFIG_PROJECT_LCD_SPI_DC_GPIO
#ifndef LCD_BL_GPIO
#define LCD_BL_GPIO CONFIG_PROJECT_LCD_BL_GPIO
#endif
#define LCD_WIDTH CONFIG_PROJECT_LCD_WIDTH
#define LCD_HEIGHT CONFIG_PROJECT_LCD_HEIGHT
#define LCD_REFRESH_RATE CONFIG_PROJECT_LCD_REFRESH_RATE
#define LCD_DEFAULT_BRIGHTNESS CONFIG_PROJECT_LCD_DEFAULT_BRIGHTNESS
#define LCD_PWM_FREQUENCY CONFIG_PROJECT_LCD_PWM_FREQUENCY

#ifdef CONFIG_PROJECT_LCD_UI_NATIVE
#define LCD_TASK_STACK_SIZE CONFIG_PROJECT_LCD_TASK_STACK_SIZE
#define LCD_TASK_PRIORITY CONFIG_PROJECT_LCD_TASK_PRIORITY
#else
#define LCD_TASK_STACK_SIZE 4096
#define LCD_TASK_PRIORITY 5
#endif

#else  /* RADAR_ENABLE_LCD_DISPLAY == 0 */

/* Defaults when LCD driver is disabled */
#define LCD_WIDTH 240
#define LCD_HEIGHT 240
#define LCD_SPI_HOST SPI2_HOST
#define LCD_SPI_CLOCK_SPEED_HZ 40000000
#ifndef LCD_SPI_MOSI_GPIO
#define LCD_SPI_MOSI_GPIO 11
#endif
#ifndef LCD_SPI_SCLK_GPIO
#define LCD_SPI_SCLK_GPIO 12
#endif
#ifndef LCD_SPI_CS_GPIO
#define LCD_SPI_CS_GPIO 13
#endif
#ifndef LCD_SPI_DC_GPIO
#define LCD_SPI_DC_GPIO 14
#endif
#ifndef LCD_BL_GPIO
#define LCD_BL_GPIO 15
#endif
#define LCD_REFRESH_RATE 30
#define LCD_DEFAULT_BRIGHTNESS 50
#define LCD_PWM_FREQUENCY 5000
#define LCD_TASK_STACK_SIZE 4096
#define LCD_TASK_PRIORITY 5

#endif /* RADAR_ENABLE_LCD_DISPLAY */

#ifdef __cplusplus
}
#endif

#endif /* LCD_CONFIG_H */
