#ifndef HEARTBEAT_SERVICE_CONFIG_H
#define HEARTBEAT_SERVICE_CONFIG_H

#include "sdkconfig.h"

/* Heartbeat Service component enable/disable switch */
#define HEARTBEAT_SERVICE_ENABLE CONFIG_HEARTBEAT_SERVICE_ENABLE

#if (HEARTBEAT_SERVICE_ENABLE == 1)

#define HEARTBEAT_SERVICE_PING_INTERVAL_SEC CONFIG_HEARTBEAT_SERVICE_PING_INTERVAL_SEC
#define HEARTBEAT_SERVICE_TIMEOUT_SEC CONFIG_HEARTBEAT_SERVICE_TIMEOUT_SEC

#endif /* HEARTBEAT_SERVICE_ENABLE */

#endif /* HEARTBEAT_SERVICE_CONFIG_H */
