/*
 * audio_service_module_config.h - Audio service module configuration (migrated from FocusLamp)
 */

#pragma once
#ifndef __AUDIO_SERVICE_MODULE_CONFIG_H__
#define __AUDIO_SERVICE_MODULE_CONFIG_H__

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C"
{
#endif

/* Enable/disable audio service module */
#ifdef CONFIG_PROJECT_ENABLE_AUDIO_SERVICE_MODULE
#define AUDIO_SERVICE_MODULE_ENABLE CONFIG_PROJECT_ENABLE_AUDIO_SERVICE_MODULE
#else
#define AUDIO_SERVICE_MODULE_ENABLE 0
#endif

#if (AUDIO_SERVICE_MODULE_ENABLE == 1)

#ifdef CONFIG_AUDIO_SERVICE_SAMPLE_RATE
#define AUDIO_SERVICE_MODULE_SAMPLE_RATE CONFIG_AUDIO_SERVICE_SAMPLE_RATE
#else
#define AUDIO_SERVICE_MODULE_SAMPLE_RATE 16000
#endif

#ifdef CONFIG_AUDIO_SERVICE_OPUS_FRAME_DURATION
#define AUDIO_SERVICE_MODULE_OPUS_FRAME_DURATION CONFIG_AUDIO_SERVICE_OPUS_FRAME_DURATION
#else
#define AUDIO_SERVICE_MODULE_OPUS_FRAME_DURATION 60
#endif

#ifdef CONFIG_AUDIO_SERVICE_TASK_STACK_SIZE
#define AUDIO_SERVICE_MODULE_TASK_STACK_SIZE CONFIG_AUDIO_SERVICE_TASK_STACK_SIZE
#else
#define AUDIO_SERVICE_MODULE_TASK_STACK_SIZE 8192
#endif

#ifdef CONFIG_AUDIO_SERVICE_TASK_PRIORITY
#define AUDIO_SERVICE_MODULE_TASK_PRIORITY CONFIG_AUDIO_SERVICE_TASK_PRIORITY
#else
#define AUDIO_SERVICE_MODULE_TASK_PRIORITY 5
#endif

#ifdef CONFIG_AUDIO_SERVICE_OPUS_ENABLE
#define AUDIO_SERVICE_MODULE_OPUS_ENABLE (CONFIG_AUDIO_SERVICE_OPUS_ENABLE == 1)
#else
#define AUDIO_SERVICE_MODULE_OPUS_ENABLE 0
#endif

#ifdef CONFIG_AUDIO_SERVICE_AEC_ENABLE
#define AUDIO_SERVICE_MODULE_AEC_ENABLE (CONFIG_AUDIO_SERVICE_AEC_ENABLE == 1)
#else
#define AUDIO_SERVICE_MODULE_AEC_ENABLE 0
#endif

#ifdef CONFIG_AUDIO_SERVICE_VAD_ENABLE
#define AUDIO_SERVICE_MODULE_VAD_ENABLE (CONFIG_AUDIO_SERVICE_VAD_ENABLE == 1)
#else
#define AUDIO_SERVICE_MODULE_VAD_ENABLE 0
#endif

#ifdef CONFIG_AUDIO_SERVICE_WAKE_WORD_ENABLE
#define AUDIO_SERVICE_MODULE_WAKE_WORD_ENABLE (CONFIG_AUDIO_SERVICE_WAKE_WORD_ENABLE == 1)
#else
#define AUDIO_SERVICE_MODULE_WAKE_WORD_ENABLE 0
#endif

#endif /* AUDIO_SERVICE_MODULE_ENABLE */

#ifdef __cplusplus
}
#endif

#endif /* __AUDIO_SERVICE_MODULE_CONFIG_H__ */
