#ifndef WEBSOCKET_MANAGER_CONFIG_H
#define WEBSOCKET_MANAGER_CONFIG_H

#include "sdkconfig.h"

/* WebSocket Manager component enable/disable switch */
#define WS_MANAGER_ENABLE CONFIG_WS_MANAGER_ENABLE

#if (WS_MANAGER_ENABLE == 1)

/* Client configuration */
#define WS_MANAGER_CLIENT_ENABLE    CONFIG_WS_MANAGER_CLIENT_ENABLE
#define WS_MANAGER_SERVER_ENABLE    CONFIG_WS_MANAGER_SERVER_ENABLE

/* Client defaults */
#define WS_MANAGER_PING_INTERVAL    CONFIG_WS_MANAGER_PING_INTERVAL
#define WS_MANAGER_RECONNECT_MS     CONFIG_WS_MANAGER_RECONNECT_TIMEOUT_MS
#define WS_MANAGER_BUFFER_SIZE      CONFIG_WS_MANAGER_BUFFER_SIZE
#define WS_MANAGER_CLIENT_URI       CONFIG_WS_MANAGER_CLIENT_URI

/* Server configuration */
#define WS_MANAGER_SERVER_PORT      CONFIG_WS_MANAGER_SERVER_PORT
#define WS_MANAGER_SERVER_MAX_CONN  CONFIG_WS_MANAGER_SERVER_MAX_CONN

/* TLS configuration */
#define WS_MANAGER_TLS_ENABLE       CONFIG_WS_MANAGER_TLS_ENABLE

#endif /* WS_MANAGER_ENABLE */

#endif /* WEBSOCKET_MANAGER_CONFIG_H */
