#ifndef CONNECTION_MANAGER_CONFIG_H
#define CONNECTION_MANAGER_CONFIG_H

#include "sdkconfig.h"

/* Connection Manager component enable/disable switch */
#define CONNECTION_MANAGER_ENABLE CONFIG_CONNECTION_MANAGER_ENABLE

#if (CONNECTION_MANAGER_ENABLE == 1)

/* WiFi connection management */
#define CONNECTION_MANAGER_WIFI_INIT_TIMEOUT_MS CONFIG_CONNECTION_MANAGER_WIFI_INIT_TIMEOUT_MS
#define CONNECTION_MANAGER_WIFI_RECONNECT_MAX_DELAY_MS CONFIG_CONNECTION_MANAGER_WIFI_RECONNECT_MAX_DELAY_MS

/* WebSocket reconnection management */
#define CONNECTION_MANAGER_WS_RECONNECT_MAX_DELAY_MS CONFIG_CONNECTION_MANAGER_WS_RECONNECT_MAX_DELAY_MS

/* Health monitoring */
#define CONNECTION_MANAGER_MONITOR_INTERVAL_MS CONFIG_CONNECTION_MANAGER_MONITOR_INTERVAL_MS

#endif /* CONNECTION_MANAGER_ENABLE */

#endif /* CONNECTION_MANAGER_CONFIG_H */
