#ifndef LCD_MODULE_CONFIG_H
#define LCD_MODULE_CONFIG_H

#include "project_config.h"
#include "sdkconfig.h"

#ifdef CONFIG_PROJECT_LCD_DRIVER_ENABLE
#define LCD_MODULE_ENABLE 1
#else
#define LCD_MODULE_ENABLE 0
#endif

#if (LCD_MODULE_ENABLE == 1)

#include "lcd_config.h"

#define LCD_MODULE_WIDTH LCD_WIDTH
#define LCD_MODULE_HEIGHT LCD_HEIGHT
#define LCD_MODULE_DC_GPIO CONFIG_PROJECT_LCD_SPI_DC_GPIO
#define LCD_MODULE_CS_GPIO CONFIG_PROJECT_LCD_SPI_CS_GPIO
#define LCD_MODULE_RST_GPIO -1

#define LCD_MODULE_ENABLE_EMOTION CONFIG_PROJECT_LCD_MODULE_ENABLE_EMOTION
#define LCD_MODULE_ENABLE_INFO CONFIG_PROJECT_LCD_MODULE_ENABLE_INFO

#endif

#endif