#ifndef MOTION_CONTROLLER_CONFIG_H
#define MOTION_CONTROLLER_CONFIG_H

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C"
{
#endif

// Module enable/disable
#ifdef CONFIG_MOTION_CONTROLLER_ENABLE
#define MOTION_CONTROLLER_ENABLE CONFIG_MOTION_CONTROLLER_ENABLE
#else
#define MOTION_CONTROLLER_ENABLE 1
#endif

// Home position defaults
#ifdef CONFIG_MOTION_HOME_EM3_POS
#define MOTION_HOME_EM3_POS CONFIG_MOTION_HOME_EM3_POS
#else
#define MOTION_HOME_EM3_POS 1500
#endif

#ifdef CONFIG_MOTION_HOME_LX1_POS
#define MOTION_HOME_LX1_POS CONFIG_MOTION_HOME_LX1_POS
#else
#define MOTION_HOME_LX1_POS 500
#endif

#ifdef CONFIG_MOTION_HOME_LX2_POS
#define MOTION_HOME_LX2_POS CONFIG_MOTION_HOME_LX2_POS
#else
#define MOTION_HOME_LX2_POS 550
#endif

#ifdef CONFIG_MOTION_HOME_LX3_POS
#define MOTION_HOME_LX3_POS CONFIG_MOTION_HOME_LX3_POS
#else
#define MOTION_HOME_LX3_POS 630
#endif

#ifdef CONFIG_MOTION_HOME_LX5_POS
#define MOTION_HOME_LX5_POS CONFIG_MOTION_HOME_LX5_POS
#else
#define MOTION_HOME_LX5_POS 420
#endif

// Home execution time
#ifdef CONFIG_MOTION_HOME_TIME_MS
#define MOTION_HOME_TIME_MS CONFIG_MOTION_HOME_TIME_MS
#else
#define MOTION_HOME_TIME_MS 1500
#endif

// Safety limits - EM3
#ifdef CONFIG_MOTION_EM3_MIN_POS
#define MOTION_EM3_MIN_POS CONFIG_MOTION_EM3_MIN_POS
#else
#define MOTION_EM3_MIN_POS 0
#endif

#ifdef CONFIG_MOTION_EM3_MAX_POS
#define MOTION_EM3_MAX_POS CONFIG_MOTION_EM3_MAX_POS
#else
#define MOTION_EM3_MAX_POS 3000
#endif

#ifdef CONFIG_MOTION_EM3_MAX_SPEED
#define MOTION_EM3_MAX_SPEED CONFIG_MOTION_EM3_MAX_SPEED
#else
#define MOTION_EM3_MAX_SPEED 2000
#endif

// Safety limits - LX
#ifdef CONFIG_MOTION_LX_MIN_POS
#define MOTION_LX_MIN_POS CONFIG_MOTION_LX_MIN_POS
#else
#define MOTION_LX_MIN_POS 0
#endif

#ifdef CONFIG_MOTION_LX_MAX_POS
#define MOTION_LX_MAX_POS CONFIG_MOTION_LX_MAX_POS
#else
#define MOTION_LX_MAX_POS 1000
#endif

#ifdef CONFIG_MOTION_LX_MAX_SPEED
#define MOTION_LX_MAX_SPEED CONFIG_MOTION_LX_MAX_SPEED
#else
#define MOTION_LX_MAX_SPEED 1000
#endif

// Focus mode limits (percentage of normal limits)
#ifdef CONFIG_MOTION_FOCUS_AMPLITUDE_RATIO
#define MOTION_FOCUS_AMPLITUDE_RATIO CONFIG_MOTION_FOCUS_AMPLITUDE_RATIO
#else
#define MOTION_FOCUS_AMPLITUDE_RATIO 30  // 30% of normal amplitude
#endif

#ifdef CONFIG_MOTION_FOCUS_SPEED_RATIO
#define MOTION_FOCUS_SPEED_RATIO CONFIG_MOTION_FOCUS_SPEED_RATIO
#else
#define MOTION_FOCUS_SPEED_RATIO 50  // 50% of normal speed
#endif

// Company mode limits
#ifdef CONFIG_MOTION_COMPANY_AMPLITUDE_RATIO
#define MOTION_COMPANY_AMPLITUDE_RATIO CONFIG_MOTION_COMPANY_AMPLITUDE_RATIO
#else
#define MOTION_COMPANY_AMPLITUDE_RATIO 50  // 50% of normal amplitude
#endif

#ifdef CONFIG_MOTION_COMPANY_SPEED_RATIO
#define MOTION_COMPANY_SPEED_RATIO CONFIG_MOTION_COMPANY_SPEED_RATIO
#else
#define MOTION_COMPANY_SPEED_RATIO 70  // 70% of normal speed
#endif

// Servo IDs
#define MOTION_SERVO_EM3_ID 4
#define MOTION_SERVO_LX_IDS {1, 2, 3, 5}
#define MOTION_SERVO_LX_COUNT 4

// Task configuration
#ifdef CONFIG_MOTION_TASK_STACK_SIZE
#define MOTION_TASK_STACK_SIZE CONFIG_MOTION_TASK_STACK_SIZE
#else
#define MOTION_TASK_STACK_SIZE 4096
#endif

#ifdef CONFIG_MOTION_TASK_PRIORITY
#define MOTION_TASK_PRIORITY CONFIG_MOTION_TASK_PRIORITY
#else
#define MOTION_TASK_PRIORITY 5
#endif

// Log enable
#ifdef CONFIG_MOTION_LOG_ENABLE
#define MOTION_LOG_ENABLE CONFIG_MOTION_LOG_ENABLE
#else
#define MOTION_LOG_ENABLE 1
#endif

#ifdef __cplusplus
}
#endif

#endif // MOTION_CONTROLLER_CONFIG_H