#ifndef SERVO_WEB_CONTROL_MODULE_CONFIG_H
#define SERVO_WEB_CONTROL_MODULE_CONFIG_H

#include "sdkconfig.h"

#ifdef CONFIG_PROJECT_ENABLE_SERVO_WEB_CONTROL
#define SERVO_WEB_CONTROL_MODULE_ENABLE 1
#else
#define SERVO_WEB_CONTROL_MODULE_ENABLE 0
#endif

// 从 Kconfig 获取配置值
#ifdef CONFIG_SERVO_WEB_CONTROL_WS_PORT
#define SERVO_WEB_CONTROL_DEFAULT_WS_PORT CONFIG_SERVO_WEB_CONTROL_WS_PORT
#else
#define SERVO_WEB_CONTROL_DEFAULT_WS_PORT 80
#endif

#ifdef CONFIG_SERVO_WEB_CONTROL_WS_ENDPOINT
#define SERVO_WEB_CONTROL_DEFAULT_WS_ENDPOINT CONFIG_SERVO_WEB_CONTROL_WS_ENDPOINT
#else
#define SERVO_WEB_CONTROL_DEFAULT_WS_ENDPOINT "/ws"
#endif

#ifdef CONFIG_SERVO_WEB_CONTROL_ENABLE_SERIAL_BRIDGE
#define SERVO_WEB_CONTROL_DEFAULT_SERIAL_BRIDGE 1
#else
#define SERVO_WEB_CONTROL_DEFAULT_SERIAL_BRIDGE 0
#endif

#endif // SERVO_WEB_CONTROL_MODULE_CONFIG_H