#ifndef LVGL_UI_CONFIG_H
#define LVGL_UI_CONFIG_H

#include "sdkconfig.h"

#ifdef CONFIG_PROJECT_LVGL_UI_ENABLE
#define LVGL_UI_ENABLE 1
#else
#define LVGL_UI_ENABLE 0
#endif

#if (LVGL_UI_ENABLE == 1)

#define LVGL_UI_LCD_WIDTH CONFIG_PROJECT_LCD_WIDTH
#define LVGL_UI_LCD_HEIGHT CONFIG_PROJECT_LCD_HEIGHT

#define LVGL_UI_BUFFER_SIZE_PERCENT CONFIG_PROJECT_LVGL_UI_BUFFER_SIZE_PERCENT

#ifdef CONFIG_PROJECT_LVGL_UI_DOUBLE_BUFFER
#define LVGL_UI_DOUBLE_BUFFER 1
#else
#define LVGL_UI_DOUBLE_BUFFER 0
#endif

#define LVGL_UI_TASK_STACK_SIZE CONFIG_PROJECT_LVGL_UI_TASK_STACK_SIZE
#define LVGL_UI_TASK_PRIORITY CONFIG_PROJECT_LVGL_UI_TASK_PRIORITY
#define LVGL_UI_TASK_PERIOD_MS CONFIG_PROJECT_LVGL_UI_TASK_PERIOD_MS

#ifdef CONFIG_PROJECT_LVGL_UI_ENABLE_EXPRESSION
#define LVGL_UI_ENABLE_EXPRESSION 1
#else
#define LVGL_UI_ENABLE_EXPRESSION 0
#endif

#ifdef CONFIG_PROJECT_LVGL_UI_ENABLE_INFO
#define LVGL_UI_ENABLE_INFO 1
#else
#define LVGL_UI_ENABLE_INFO 0
#endif

#ifdef CONFIG_PROJECT_LVGL_UI_ENABLE_RADAR_VIEW
#define LVGL_UI_ENABLE_RADAR_VIEW 1
#else
#define LVGL_UI_ENABLE_RADAR_VIEW 0
#endif

#ifdef CONFIG_PROJECT_LVGL_UI_ENABLE_ENCODER
#define LVGL_UI_ENABLE_ENCODER 1
#else
#define LVGL_UI_ENABLE_ENCODER 0
#endif

#if (LVGL_UI_ENABLE_ENCODER == 1)
#define LVGL_UI_ENCODER_A_GPIO CONFIG_PROJECT_LVGL_UI_ENCODER_A_GPIO
#define LVGL_UI_ENCODER_B_GPIO CONFIG_PROJECT_LVGL_UI_ENCODER_B_GPIO
#define LVGL_UI_ENCODER_BTN_GPIO CONFIG_PROJECT_LVGL_UI_ENCODER_BTN_GPIO
#endif

#ifdef CONFIG_PROJECT_LVGL_UI_ENABLE_SYSMON_PERF
#define LVGL_UI_ENABLE_SYSMON_PERF 1
#else
#define LVGL_UI_ENABLE_SYSMON_PERF 0
#endif

#ifdef CONFIG_PROJECT_LVGL_UI_ENABLE_SYSMON_MEM
#define LVGL_UI_ENABLE_SYSMON_MEM 1
#else
#define LVGL_UI_ENABLE_SYSMON_MEM 0
#endif

#endif

#endif
