/*
 * servo_service_config.h - Servo service configuration (defaults)
 */

#pragma once
#ifndef __SERVO_SERVICE_CONFIG_H__
#define __SERVO_SERVICE_CONFIG_H__

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Enable/disable servo recording/playback module */
#ifdef CONFIG_SERVO_SERVICE_ENABLE
#define SERVO_SERVICE_ENABLE CONFIG_SERVO_SERVICE_ENABLE
#else
#define SERVO_SERVICE_ENABLE 1
#endif

#if (SERVO_SERVICE_ENABLE == 1)

/* Recording slots and frames */
#ifdef CONFIG_SERVO_SERVICE_MAX_SLOTS
#define SERVO_SERVICE_MAX_SLOTS CONFIG_SERVO_SERVICE_MAX_SLOTS
#else
#define SERVO_SERVICE_MAX_SLOTS 3
#endif

#ifdef CONFIG_SERVO_SERVICE_MAX_FRAMES
#define SERVO_SERVICE_MAX_FRAMES CONFIG_SERVO_SERVICE_MAX_FRAMES
#else
#define SERVO_SERVICE_MAX_FRAMES 2000
#endif

#ifdef CONFIG_SERVO_SERVICE_SAMPLING_MS
#define SERVO_SERVICE_SAMPLING_MS CONFIG_SERVO_SERVICE_SAMPLING_MS
#else
#define SERVO_SERVICE_SAMPLING_MS 30
#endif

#ifdef CONFIG_SERVO_SERVICE_PLAYBACK_SPEED
#define SERVO_SERVICE_PLAYBACK_SPEED CONFIG_SERVO_SERVICE_PLAYBACK_SPEED
#else
#define SERVO_SERVICE_PLAYBACK_SPEED 10
#endif

/* Servo IDs */
#ifdef CONFIG_SERVO_SERVICE_EM3_ID
#define SERVO_SERVICE_EM3_ID CONFIG_SERVO_SERVICE_EM3_ID
#else
#define SERVO_SERVICE_EM3_ID 4
#endif

#ifdef CONFIG_SERVO_SERVICE_LX_COUNT
#define SERVO_SERVICE_LX_COUNT CONFIG_SERVO_SERVICE_LX_COUNT
#else
#define SERVO_SERVICE_LX_COUNT 4
#endif

#ifdef CONFIG_SERVO_SERVICE_EM3_DEFAULT_SPEED
#define SERVO_SERVICE_EM3_DEFAULT_SPEED CONFIG_SERVO_SERVICE_EM3_DEFAULT_SPEED
#else
#define SERVO_SERVICE_EM3_DEFAULT_SPEED 400
#endif

#ifdef CONFIG_SERVO_SERVICE_EM3_MIN_SPEED
#define SERVO_SERVICE_EM3_MIN_SPEED CONFIG_SERVO_SERVICE_EM3_MIN_SPEED
#else
#define SERVO_SERVICE_EM3_MIN_SPEED 10
#endif

#ifdef CONFIG_SERVO_SERVICE_EM3_MAX_SPEED
#define SERVO_SERVICE_EM3_MAX_SPEED CONFIG_SERVO_SERVICE_EM3_MAX_SPEED
#else
#define SERVO_SERVICE_EM3_MAX_SPEED 2000
#endif

#ifdef CONFIG_SERVO_SERVICE_EM3_POSITION_THRESHOLD
#define SERVO_SERVICE_EM3_POSITION_THRESHOLD CONFIG_SERVO_SERVICE_EM3_POSITION_THRESHOLD
#else
#define SERVO_SERVICE_EM3_POSITION_THRESHOLD 1500
#endif

/* Home positions */
#ifdef CONFIG_SERVO_SERVICE_HOME_EM3_POS
#define SERVO_SERVICE_HOME_EM3_POS CONFIG_SERVO_SERVICE_HOME_EM3_POS
#else
#define SERVO_SERVICE_HOME_EM3_POS 1500
#endif

#ifdef CONFIG_SERVO_SERVICE_HOME_LX_POS_1
#define SERVO_SERVICE_HOME_LX_POS_1 CONFIG_SERVO_SERVICE_HOME_LX_POS_1
#else
#define SERVO_SERVICE_HOME_LX_POS_1 500
#endif

#ifdef CONFIG_SERVO_SERVICE_HOME_LX_POS_2
#define SERVO_SERVICE_HOME_LX_POS_2 CONFIG_SERVO_SERVICE_HOME_LX_POS_2
#else
#define SERVO_SERVICE_HOME_LX_POS_2 550
#endif

#ifdef CONFIG_SERVO_SERVICE_HOME_LX_POS_3
#define SERVO_SERVICE_HOME_LX_POS_3 CONFIG_SERVO_SERVICE_HOME_LX_POS_3
#else
#define SERVO_SERVICE_HOME_LX_POS_3 630
#endif

#ifdef CONFIG_SERVO_SERVICE_HOME_LX_POS_5
#define SERVO_SERVICE_HOME_LX_POS_5 CONFIG_SERVO_SERVICE_HOME_LX_POS_5
#else
#define SERVO_SERVICE_HOME_LX_POS_5 420
#endif

/* Position limits */
#ifdef CONFIG_SERVO_SERVICE_EM3_MIN_POS
#define SERVO_SERVICE_EM3_MIN_POS CONFIG_SERVO_SERVICE_EM3_MIN_POS
#else
#define SERVO_SERVICE_EM3_MIN_POS 0
#endif

#ifdef CONFIG_SERVO_SERVICE_EM3_MAX_POS
#define SERVO_SERVICE_EM3_MAX_POS CONFIG_SERVO_SERVICE_EM3_MAX_POS
#else
#define SERVO_SERVICE_EM3_MAX_POS 3000
#endif

#ifdef CONFIG_SERVO_SERVICE_LX_MIN_POS
#define SERVO_SERVICE_LX_MIN_POS CONFIG_SERVO_SERVICE_LX_MIN_POS
#else
#define SERVO_SERVICE_LX_MIN_POS 0
#endif

#ifdef CONFIG_SERVO_SERVICE_LX_MAX_POS
#define SERVO_SERVICE_LX_MAX_POS CONFIG_SERVO_SERVICE_LX_MAX_POS
#else
#define SERVO_SERVICE_LX_MAX_POS 1000
#endif

/* Smooth motion step interval */
#ifdef CONFIG_SERVO_SERVICE_SMOOTH_STEP_MS
#define SERVO_SERVICE_SMOOTH_STEP_MS CONFIG_SERVO_SERVICE_SMOOTH_STEP_MS
#else
#define SERVO_SERVICE_SMOOTH_STEP_MS 20
#endif

#endif /* SERVO_SERVICE_ENABLE */

#ifdef __cplusplus
}
#endif

#endif /* __SERVO_SERVICE_CONFIG_H__ */
