#pragma once

#include "driver/gpio.h"
#include "driver/uart.h"
#include "sdkconfig.h"

#ifdef __cplusplus
extern "C"
{
#endif

/* Version Information */
#define RADAR_VERSION_MAJOR 1
#define RADAR_VERSION_MINOR 0
#define RADAR_VERSION_REVISION 0
#define RADAR_VERSION_STRING "1.0.0"
#define RADAR_BUILD_DATE __DATE__
#define RADAR_BUILD_TIME __TIME__

/* Radar project selection */
#define RADAR_PROJECT_BREATH 1
#define RADAR_PROJECT_GESTURE 2
#define RADAR_CURRENT_PROJECT RADAR_PROJECT_BREATH

/* Hardware Pin Configuration (defaults when Kconfig options not set) */

/* Radar driver master enable (0 = skip init when hardware not connected).
 * Auto-enabled when CONFIG_PROJECT_RADAR_DRIVER_ENABLE is set in Kconfig. */
#ifndef RADAR_DRIVER_ENABLE
#ifdef CONFIG_PROJECT_RADAR_DRIVER_ENABLE
#define RADAR_DRIVER_ENABLE 1
#else
#define RADAR_DRIVER_ENABLE 0
#endif
#endif

#ifdef CONFIG_PROJECT_RADAR_DRIVER_ENABLE
#define RADAR_UART_PORT CONFIG_PROJECT_RADAR_UART_PORT
#define RADAR_UART_BAUD_RATE CONFIG_PROJECT_RADAR_UART_BAUD_RATE
#define RADAR_UART_TX_GPIO CONFIG_PROJECT_RADAR_UART_TX_GPIO
#define RADAR_UART_RX_GPIO CONFIG_PROJECT_RADAR_UART_RX_GPIO
#else
#define RADAR_UART_PORT 1
#define RADAR_UART_BAUD_RATE 115200
#define RADAR_UART_TX_GPIO 1
#define RADAR_UART_RX_GPIO 7
#endif

#ifdef CONFIG_PROJECT_LED_DRIVER_ENABLE
#define WS2812_GPIO CONFIG_PROJECT_LED_WS2812_GPIO
#define WS2812_LED_COUNT CONFIG_PROJECT_LED_WS2812_LED_COUNT
#define GPIO_LED_PIN CONFIG_PROJECT_LED_GPIO_PIN
#define GPIO_LED_ACTIVE_HIGH CONFIG_PROJECT_LED_GPIO_ACTIVE_HIGH
#else
#define WS2812_GPIO 6
#define WS2812_LED_COUNT 1
#define GPIO_LED_PIN 6
#define GPIO_LED_ACTIVE_HIGH 1
#endif

/* UART hardware configuration */
#define RADAR_UART_RTS_GPIO UART_PIN_NO_CHANGE
#define RADAR_UART_CTS_GPIO UART_PIN_NO_CHANGE
#define RADAR_UART_DATA_BITS UART_DATA_8_BITS
#define RADAR_UART_PARITY UART_PARITY_DISABLE
#define RADAR_UART_STOP_BITS UART_STOP_BITS_1
#define RADAR_UART_FLOW_CTRL UART_HW_FLOWCTRL_DISABLE
#define RADAR_UART_SOURCE_CLK UART_SCLK_DEFAULT

/* Task defaults */
#define RADAR_TASK_STACK_SIZE 4096
#define RADAR_TASK_PRIORITY 5
#define RADAR_TASK_PERIOD_MS 100

/* Frame queue */
#define RADAR_FRAME_QUEUE_SIZE 10

/* UART buffer */
#define RADAR_UART_EVENT_QUEUE_LEN 20
#define RADAR_UART_RX_BUFFER_SIZE 1024
#define RADAR_UART_TX_BUFFER_SIZE 0

/* WS2812 */
#define WS2812_RMT_RESOLUTION_HZ 10000000

/* TF Parser defaults */
#define RADAR_TF_SOF 0x7E
#define RADAR_TF_HEADER_SIZE 8
#define RADAR_TF_MIN_FRAME_SIZE 9
#define RADAR_TF_MAX_PAYLOAD_SIZE 128
#define RADAR_TF_MAX_FRAME_SIZE (RADAR_TF_HEADER_SIZE + RADAR_TF_MAX_PAYLOAD_SIZE + 1)
#define RADAR_MAX_CONSECUTIVE_ERRORS 10
#define RADAR_DATA_TIMEOUT_MS 5000
#define RADAR_IDLE_AUTO_STOP_ENABLE 1
#define RADAR_IDLE_AUTO_STOP_TIMEOUT_MS 0

/* Radar message types */
#define RADAR_MSG_TYPE_FIRMWARE_STATUS 0xFFFF
#define RADAR_MSG_TYPE_HUMAN_DETECT 0x0F09
#define RADAR_MSG_TYPE_POSITION 0x0A04
#define RADAR_MSG_TYPE_PHASE_TEST 0x0A13
#define RADAR_MSG_TYPE_BREATH_RATE 0x0A14
#define RADAR_MSG_TYPE_HEART_RATE 0x0A15
#define RADAR_MSG_TYPE_TARGET_RANGE 0x0A18
#define RADAR_MSG_TYPE_TARGET_TRACK 0x0A17

/* Feature defaults */
#define RADAR_ENABLE_RADAR_SYSTEM 1
#define RADAR_ENABLE_HRV_ANALYSIS 0
#define RADAR_ENABLE_PRESENCE_DETECTION 1
#define RADAR_ENABLE_BREATH_DETECTION 0
#define RADAR_ENABLE_SEDENTARY_DETECTION 0
#define RADAR_ENABLE_LED_AUTO_OFF 0
#define RADAR_ENABLE_LED_DISPLAY 1
#define MOTION_ANALYZER_LOG_ENABLE 0
#define HRV_ANALYZER_LOG_ENABLE 0
#define RADAR_MODULE_LOG_ENABLE 0
#define LED_MODULE_LOG_ENABLE 0
#define LCD_MODULE_LOG_ENABLE 0
#define SERVO_MODULE_LOG_ENABLE 0
#define EVENT_BUS_LOG_ENABLE 0

#ifdef __cplusplus
}
#endif
