#ifndef SERVO_CONTROL_MODULE_CONFIG_H
#define SERVO_CONTROL_MODULE_CONFIG_H

#include "project_config.h"
#include "sdkconfig.h"

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef CONFIG_PROJECT_ENABLE_SERVO_CONTROL
#define SERVO_CONTROL_MODULE_ENABLE 1
#else
#define SERVO_CONTROL_MODULE_ENABLE 0
#endif

#if (SERVO_CONTROL_MODULE_ENABLE == 1)

#define SERVO_CONTROL_MAX_SLOTS CONFIG_SERVO_CONTROL_MAX_SLOTS
#define SERVO_CONTROL_MAX_FRAMES CONFIG_SERVO_CONTROL_MAX_FRAMES
#define SERVO_CONTROL_SAMPLING_MS CONFIG_SERVO_CONTROL_SAMPLING_MS
#define SERVO_CONTROL_PLAYBACK_SPEED_MULTIPLIER CONFIG_SERVO_CONTROL_PLAYBACK_SPEED_MULTIPLIER
#define SERVO_CONTROL_EM3_ID CONFIG_SERVO_CONTROL_EM3_ID
#define SERVO_CONTROL_LX_COUNT CONFIG_SERVO_CONTROL_LX_COUNT
#define SERVO_CONTROL_EM3_DEFAULT_SPEED CONFIG_SERVO_CONTROL_EM3_DEFAULT_SPEED
#define SERVO_CONTROL_EM3_MIN_SPEED CONFIG_SERVO_CONTROL_EM3_MIN_SPEED
#define SERVO_CONTROL_EM3_MAX_SPEED CONFIG_SERVO_CONTROL_EM3_MAX_SPEED

#ifdef CONFIG_SERVO_CONTROL_EM3_POSITION_THRESHOLD
#define SERVO_CONTROL_EM3_POSITION_THRESHOLD CONFIG_SERVO_CONTROL_EM3_POSITION_THRESHOLD
#else
#define SERVO_CONTROL_EM3_POSITION_THRESHOLD 1500
#endif

#ifdef CONFIG_PROJECT_APP_LOG_ENABLE_SERVO_MODULE
#define SERVO_MODULE_LOG_ENABLE 1
#else
#define SERVO_MODULE_LOG_ENABLE 0
#endif

#endif

#ifdef __cplusplus
}
#endif

#endif
